version: '3.8'
services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: glaxierpassword
    volumes:
      - postgres:/data/postgres
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: glaxier
      KEYCLOAK_ADMIN_PASSWORD: glaxierpassword
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: glaxier
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: glaxierpassword
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres: